### ISSUE TITLE
Picked map makes stats vanish

### ISSUE THREAD

**Issue by Smooginozaure** [rodolphebarbanneau/suntzu#1]
When you're in the matchroom, you can see the whole maps stats.
As soon as the map is picked up, the stats are vanishing, making it impossible to check later.

Steps to reproduce the behavior :
1. Start a matchmaking
2. When the lobby is created, the stats are shown correctly
3. When the map voting is over and the map is picked, the stats are vanishing

**Expected behavior**
Stats should stay correctly to keep an eye on them once the map vote is over.

**Screenshots**

![Opera Instantané_2023-10-05_171928_www faceit com](https://github.com/rodolphebarbanneau/suntzu/assets/129693077/274351bb-9d16-46f4-92bd-319dd71d962e)

**Desktop (please complete the following information):**
 - OS : Windows 11
 - Browser : Opéra (102.0.4880.78

**Comment by rodolphebarbanneau** [comment]
Fixed with 725cee75ac635100550436feaf4cab03ae9306fe
