### ISSUE TITLE
Marking a player as non-desirable

### ISSUE THREAD

**Issue by Smooginozaure** [rodolphebarbanneau/suntzu#3]
When you have a bad experience with someone, you may not want to play with him again.
A cool idea could be to mark a player as non-desirable.
This could lead to display the player with a specific color (in your group, for example).
So on, you'll receive a notice that you had a previous bad experience with him, and then you can avoid him, or leave the group.

**Comment by rodolphebarbanneau** [comment]
Thanks for the idea! We get where you're coming from, but we're not looking to add that feature anytime soon. Appreciate the input, though!
